In [1]:
import torch

In [2]:
a=torch.ones(3)
a

tensor([1., 1., 1.])

In [3]:
a[1]

tensor(1.)

In [4]:
float(a[1])

1.0

In [6]:
a[2]=2.0
a

tensor([1., 1., 2.])

In [7]:
points=torch.zeros(6)

In [8]:
points[0]=4.0
points[1]=1.0
points[2]=5.0
points[3]=3.0
points[4]=2.0
points[5]=1.0
points

tensor([4., 1., 5., 3., 2., 1.])

In [9]:
points=torch.tensor([4.0,1.0,5.0,3.0,2.0,1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [10]:
float(points[0]),float(points[1])

(4.0, 1.0)

In [11]:
points=torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [12]:
points.shape

torch.Size([3, 2])

In [13]:
points=torch.zeros(3,2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [14]:
points=torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [16]:
points[0,1]

tensor(1.)

In [17]:
some_list=list(range(6))
some_list

[0, 1, 2, 3, 4, 5]

In [18]:
some_list[1:4:2]

[1, 3]

In [19]:
points[1:]

tensor([[5., 3.],
        [2., 1.]])

In [20]:
points[1:,:]

tensor([[5., 3.],
        [2., 1.]])

In [21]:
points[1:,0]

tensor([5., 2.])

In [23]:
points[None]

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])